services:
  clientvault:
    network_mode: host
    build:
      context: ./clientvault
      dockerfile: Dockerfile
    container_name: clientvault
    volumes:
      - ./clientvault:/app
    ports:
      - "${APP_PORT}:${APP_PORT}"
    env_file:
      - .env
