"""migrations

Revision ID: 207ffb7ff754
Revises: 
Create Date: 2025-03-27 13:47:22.669396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '207ffb7ff754'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente_status',
    sa.Column('id_status', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo_cliente', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id_status')
    )
    op.create_table('potencial_client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pnombre', sa.String(length=50), nullable=False),
    sa.Column('snombre', sa.String(length=50), nullable=True),
    sa.Column('appaterno', sa.String(length=50), nullable=False),
    sa.Column('apmaterno', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('numero_telefono', sa.String(length=20), nullable=True),
    sa.Column('razon_contacto', sa.Text(), nullable=True),
    sa.Column('cliente_status_id', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_status_id'], ['cliente_status.id_status'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_potencial_client_id'), 'potencial_client', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_potencial_client_id'), table_name='potencial_client')
    op.drop_table('potencial_client')
    op.drop_table('cliente_status')
    # ### end Alembic commands ###
