"""migrations

Revision ID: 5c3b0df38f51
Revises: 
Create Date: 2025-03-27 13:31:08.496511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c3b0df38f51'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('identificacion',
    sa.Column('id_identificacion', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('n_documeto', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id_identificacion')
    )
    op.create_table('nvacademico',
    sa.Column('id_academiconv', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('n_academiconv', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_academiconv')
    )
    op.create_table('pais',
    sa.Column('id_pais', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('iso', sa.String(length=2), nullable=True),
    sa.Column('isonum', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id_pais')
    )
    op.create_table('prevision',
    sa.Column('id_prevision', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo_prev', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_prevision')
    )
    op.create_table('region',
    sa.Column('id_region', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('n_region', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_region')
    )
    op.create_table('sector',
    sa.Column('id_sector', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo_sector', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_sector')
    )
    op.create_table('sucursal',
    sa.Column('id_sucursal', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sucursal', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_sucursal')
    )
    op.create_table('telefonos',
    sa.Column('id_telefonos', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('celular', sa.String(length=15), nullable=False),
    sa.Column('tel_fijo', sa.String(length=15), nullable=True),
    sa.Column('familiar', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id_telefonos')
    )
    op.create_table('users',
    sa.Column('id_user', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_user')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_table('comuna',
    sa.Column('id_comuna', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('n_comuna', sa.String(length=100), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['region.id_region'], ),
    sa.PrimaryKeyConstraint('id_comuna')
    )
    op.create_table('ocupacion',
    sa.Column('id_ocupacion', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sector_id', sa.Integer(), nullable=False),
    sa.Column('tipo_ocupacion', sa.String(length=75), nullable=False),
    sa.ForeignKeyConstraint(['sector_id'], ['sector.id_sector'], ),
    sa.PrimaryKeyConstraint('id_ocupacion')
    )
    op.create_table('direccion',
    sa.Column('id_direccion', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('direccion', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.String(length=1000), nullable=True),
    sa.Column('comuna_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comuna_id'], ['comuna.id_comuna'], ),
    sa.PrimaryKeyConstraint('id_direccion')
    )
    op.create_table('paciente',
    sa.Column('id_paciente', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.LargeBinary(length=25), nullable=False),
    sa.Column('pnombre', sa.String(length=50), nullable=False),
    sa.Column('snombre', sa.String(length=50), nullable=True),
    sa.Column('appaterno', sa.String(length=100), nullable=False),
    sa.Column('apmaterno', sa.String(length=100), nullable=True),
    sa.Column('pais_id', sa.Integer(), nullable=False),
    sa.Column('identificacion_id', sa.Integer(), nullable=False),
    sa.Column('num_identificacion', sa.String(length=20), nullable=True),
    sa.Column('f_reg_alma', sa.Date(), nullable=False),
    sa.Column('f_nac', sa.Date(), nullable=False),
    sa.Column('genero', sa.String(length=10), nullable=False),
    sa.Column('prevision_id', sa.Integer(), nullable=False),
    sa.Column('ocupacion_id', sa.Integer(), nullable=False),
    sa.Column('telefono_id', sa.Integer(), nullable=False),
    sa.Column('direccion_id', sa.Integer(), nullable=False),
    sa.Column('sucursal_id', sa.Integer(), nullable=False),
    sa.Column('academico_id', sa.Integer(), nullable=False),
    sa.Column('mail_princ', sa.String(length=255), nullable=False),
    sa.Column('mail_sec', sa.String(length=255), nullable=True),
    sa.Column('ult_visita', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['academico_id'], ['nvacademico.id_academiconv'], ),
    sa.ForeignKeyConstraint(['direccion_id'], ['direccion.id_direccion'], ),
    sa.ForeignKeyConstraint(['identificacion_id'], ['identificacion.id_identificacion'], ),
    sa.ForeignKeyConstraint(['ocupacion_id'], ['ocupacion.id_ocupacion'], ),
    sa.ForeignKeyConstraint(['pais_id'], ['pais.id_pais'], ),
    sa.ForeignKeyConstraint(['prevision_id'], ['prevision.id_prevision'], ),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursal.id_sucursal'], ),
    sa.ForeignKeyConstraint(['telefono_id'], ['telefonos.id_telefonos'], ),
    sa.PrimaryKeyConstraint('id_paciente')
    )
    op.create_index(op.f('ix_paciente_id_paciente'), 'paciente', ['id_paciente'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_paciente_id_paciente'), table_name='paciente')
    op.drop_table('paciente')
    op.drop_table('direccion')
    op.drop_table('ocupacion')
    op.drop_table('comuna')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('telefonos')
    op.drop_table('sucursal')
    op.drop_table('sector')
    op.drop_table('region')
    op.drop_table('prevision')
    op.drop_table('pais')
    op.drop_table('nvacademico')
    op.drop_table('identificacion')
    # ### end Alembic commands ###
