"""migrations

Revision ID: bca7af3b5f0b
Revises: 
Create Date: 2025-03-31 14:40:13.922540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bca7af3b5f0b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telefonos',
    sa.Column('id_telefonos', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('celular', sa.String(length=15), nullable=False),
    sa.Column('tel_fijo', sa.String(length=15), nullable=True),
    sa.Column('familiar', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id_telefonos')
    )
    op.create_table('direccion',
    sa.Column('id_direccion', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('direccion', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.String(length=1000), nullable=True),
    sa.Column('comuna_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comuna_id'], ['comuna.id_comuna'], ),
    sa.PrimaryKeyConstraint('id_direccion')
    )
    op.create_table('paciente',
    sa.Column('id_paciente', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.CHAR(length=36), nullable=False),
    sa.Column('pnombre', sa.String(length=50), nullable=False),
    sa.Column('snombre', sa.String(length=50), nullable=True),
    sa.Column('appaterno', sa.String(length=100), nullable=False),
    sa.Column('apmaterno', sa.String(length=100), nullable=True),
    sa.Column('pais_id', sa.Integer(), nullable=False),
    sa.Column('identificacion_id', sa.Integer(), nullable=False),
    sa.Column('num_identificacion', sa.String(length=20), nullable=True),
    sa.Column('f_reg_alma', sa.Date(), nullable=False),
    sa.Column('f_nac', sa.Date(), nullable=False),
    sa.Column('genero', sa.String(length=10), nullable=False),
    sa.Column('prevision_id', sa.Integer(), nullable=False),
    sa.Column('ocupacion_id', sa.Integer(), nullable=False),
    sa.Column('telefono_id', sa.Integer(), nullable=False),
    sa.Column('direccion_id', sa.Integer(), nullable=False),
    sa.Column('sucursal_id', sa.Integer(), nullable=False),
    sa.Column('academico_id', sa.Integer(), nullable=False),
    sa.Column('mail_princ', sa.String(length=255), nullable=False),
    sa.Column('mail_sec', sa.String(length=255), nullable=True),
    sa.Column('ult_visita', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['academico_id'], ['nvacademico.id_academiconv'], ),
    sa.ForeignKeyConstraint(['direccion_id'], ['direccion.id_direccion'], ),
    sa.ForeignKeyConstraint(['identificacion_id'], ['identificacion.id_identificacion'], ),
    sa.ForeignKeyConstraint(['ocupacion_id'], ['ocupacion.id_ocupacion'], ),
    sa.ForeignKeyConstraint(['pais_id'], ['pais.id_pais'], ),
    sa.ForeignKeyConstraint(['prevision_id'], ['prevision.id_prevision'], ),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursal.id_sucursal'], ),
    sa.ForeignKeyConstraint(['telefono_id'], ['telefonos.id_telefonos'], ),
    sa.PrimaryKeyConstraint('id_paciente')
    )
    op.create_index(op.f('ix_paciente_id_paciente'), 'paciente', ['id_paciente'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_paciente_id_paciente'), table_name='paciente')
    op.drop_table('paciente')
    op.drop_table('direccion')
    op.drop_table('telefonos')
    # ### end Alembic commands ###
